### ISSUE TITLE
Populate the database with JSON file

### ISSUE THREAD

**Issue by ilikomanov** [thewickermilko/DatingApp-net8#39]

**Comment by thewickermilko** [comment]
[eab4eef](https://github.com/thewickermilko/DatingApp-net8/commit/eab4eefacdcaf24a9098750b77d4aae4bae59d27)
 -
Created "UserSeedData.json" - JSON file for the users in the DB.
https://json-generator.com/# - used to create 10 users with random data.

**Comment by thewickermilko** [comment]
[eab4eef](https://github.com/thewickermilko/DatingApp-net8/commit/eab4eefacdcaf24a9098750b77d4aae4bae59d27)
Created "UserSeedData.json" - JSON file for the users in the DB.
https://json-generator.com/# - used to create 10 users with random data.

**Comment by thewickermilko** [comment]
[4e7d7ce](https://github.com/thewickermilko/DatingApp-net8/commit/4e7d7cebdb8ccf94b08651718059619610902921) -
Created "Seed" class.
